### ISSUE TITLE
Publish to the npm registry

### ISSUE THREAD

**Issue by parris** [aFarkas/html5shiv#163]
Hi,
Would you mind publishing versions to the npm registry? 

While having a package.json and linking to github works, you get a reinstall of the package every time you type `npm install`. html5shiv has no dependents so it seems quick, but in fact it should be hitting github everytime and possibly decompressing a tarball.

**Comment by blazzy** [comment]
Someone finally did: https://www.npmjs.com/package/html5shiv

**Comment by avindra** [comment]
This should be closed:

https://github.com/aFarkas/html5shiv/commits/master/package.json

**Comment by GeyseR** [comment]
`npm install html5shiv` command says that there is html5shiv package not found. Error entries from nmp log:
```
http GET https://registry.npmjs.org/html5shiv
http 404 https://registry.npmjs.org/html5shiv
error 404 Not Found
error 404
error 404 'html5shiv' is not in the npm registry.
error 404 You should bug the author to publish it

``` 

Package's state in npmjs registry for v3.7.2 is unpublished. See https://registry.npmjs.org/html5shiv
Since we [can't republish same version to npm registry](https://github.com/npm/npm-registry-couchapp/issues/148) we should bump version in packages.json to 3.7.3-pre as we did for all version numbers in https://github.com/aFarkas/html5shiv/commit/0a7343bff62fc032a426c39e50cfd5c95855a701 and publish it to registry.

**Comment by GeyseR** [comment]
Or we should just finally release 3.7.3 version (without `pre` suffix) and update versions in bower.json and in package.json

**Comment by aFarkas** [comment]
I would go with the last one, but I'm not the owner of the npm module.

@damnedest
Would you please be so kind to transfer ownership?

**Comment by damnedest** [comment]
You have to create your own repo, as I know.

**Comment by damnedest** [comment]
As I know.

**Comment by GeyseR** [comment]
@damnedest 
as said in npm docs you can add additional owners to package as current owner 
https://docs.npmjs.com/cli/owner

**Comment by damnedest** [comment]
https://www.npmjs.com/~damnedest

**Comment by cariseterravion** [comment]
Any estimate as to when the package will be published on npm?

**Comment by andymost** [comment]
:+1:

**Comment by jedireza** [comment]
@aFarkas @damnedest have you reached out to the npm team to get help resolving this?

**Comment by Atheryl** [comment]
+1

**Comment by aFarkas** [comment]
@jedireza 
Yes, I reached out to the npm support 4 days ago. Initially they said, well html5shiv is now available and I simply should publish with a new version to it. I immediately answered, that exactly this is the problem and I don't have permissions to do so.

To this last reply I have no answer yet. I again mailed them today by replying to the old support ticket as also by creating a new one. I hope I get an answer soon and please in case html5shiv should be available to be publish against. Don't do this your own. I will do it as as soon as I'm informed, it is possible again.

**Comment by ehsalazar** [comment]
@aFarkas 

I've attempted to reply back via the npm support ticket but I'm not sure if you're receiving my messages. Here's the last one I sent...just after 12:00pm PST, July 20, 2015.

```
It appeared that someone attempted to take over the name space then attempted to unpublish again. I believe we've corrected the issue.

It’s all yours now, but you won’t be able to re-use any version numbers used by the previous author. In fact, I'd suggest publishing your first update as a major release, i.e., v4.0.0

Please let me know if there is anything else I can do for you. I’ll be here to help.
Ernie
```

Could you give the publish another attempt? Thanks!

**Comment by aFarkas** [comment]
@ehsalazar 
I got your mails now too. Thanks for your help!

**Comment by cariseterravion** [comment]
@aFarkas @ehsalazar Thank you!
