### ISSUE TITLE
Inline svg inside <header> in IE8

### ISSUE THREAD

**Issue by nathansh** [aFarkas/html5shiv#172]
I just discovered that if you put an inline svg inside of a `<header>` element with the html5shiv included, the `<header>` element does not close. This codepen shows the code required to reproduce the issue http://codepen.io/nathansh/pen/gbMdyG. Codepen doesn't work in IE8 but you can download a zip of the code.

**Comment by Ghostavio** [comment]
there was any fix for it or it was just by removing the `xmlns`?
what if this is not an option?
