### ISSUE TITLE
license unclear

### ISSUE THREAD

**Issue by pansen** [aFarkas/html5shiv#174]
hey there, 

thanks for your great library. we want to use it in a project, but need to clarify if your lib has GPL2 or MIT license. the license file itself is a bit confusing about that. 

thanks a lot, andi

**Comment by pansen** [comment]
do you think there is a chance to shed some light into this issue during that week? otherwise we have to remove your library. would be a shame if its not a problem to clarify that license. 

best, andi

**Comment by aFarkas** [comment]
@pansen 

It's dual licensed. This means you (not me) can choose what license you want it to be.

**Comment by pansen** [comment]
awesome :) thanks for answering. 

i created a pull request to make this a bit more clear, especially for people like lawyers (...) 
https://github.com/aFarkas/html5shiv/pull/175/files

would be great if you don't mind merging this one. 

thanks and best regards, andi

**Comment by SodY2** [comment]
@aFarkas came to the same point today. thanks for your anwser! 
https://github.com/aFarkas/html5shiv/pull/175/files 
makes it a bit more understandable, it would be great if you could review it!

**Comment by pansen** [comment]
thanks a lot for accepting the pr :)
