### ISSUE TITLE
Uncaught ReferenceError: lazySizes is not defined

### ISSUE THREAD

**Issue by Semigradsky** [aFarkas/html5shiv#179]
What is this variable? https://github.com/aFarkas/html5shiv/blob/master/src/html5shiv.js#L321-L325
Looks like this is not defined.

I got this error when trying use last version with webpack.

**Comment by aFarkas** [comment]
This is simply just an embarrassing copy paste error. Thank you!

**Comment by Semigradsky** [comment]
@aFarkas Thanks, now working good with webpack! :+1: 
It would be great if new version was be pushed to npm.
