### ISSUE TITLE
header is remove from the document under IE7/IE5

### ISSUE THREAD

**Issue by dotku** [aFarkas/html5shiv#181]
here is my code

	
	<style>
		footer {
			background-color: #fec;
		}
		header {
			background-color: #efc;
		}
	</style>
	<header>
		HEADER-TEXT
	</header>
		CONTENT
	<footer>
		HELLO-TEXT
	</footer>

**Comment by RaymondDragon** [comment]
Hello ... This is a new update ?

**Comment by aFarkas** [comment]
Use ``head`` and ``body`` elements.
