### ISSUE TITLE
The 3.7.2 version is missing from the json on registry.npmjs.org

### ISSUE THREAD

**Issue by emeagher** [aFarkas/html5shiv#191]
If I go here: http://registry.npmjs.org/html5shiv

I don't see the 3.7.2 version listed under the 'versions' element. I'm not ready to upgrade to 3.7.3 yet so it's causing me problems.

Thank you,

Ed

**Comment by aFarkas** [comment]
The old versions of html5shiv weren't owned by me. the former owner has unpublished them. I'm not able to re-publish old version. But I'm really not sure what's the problem, there is not really a big difference between 3.7.2 and 3.7.3. Why can't you upgrade?

**Comment by emeagher** [comment]
Understood about the publishing. I'll get ready to upgrade :-)

Thanks for you quick reply.
