### ISSUE TITLE
I am realy sorry

### ISSUE THREAD

**Issue by plutonium150** [aFarkas/html5shiv#205]
**# 

> Excuse me, I am very izvenyayus, for the fact that I have changed the values ​​in your files, even though they are not much larger, I mixed up your project with your sleepy, excuse me please ...

**

**Comment by Valladim66** [comment]
Nothing to worry dear aFarkas! Thank you for trying to apologize even in Russian! I even forgot what kind of file is it.
I'm from Russia, my name is Vadim(it's real name)
