### ISSUE TITLE
RIP html5shiv

### ISSUE THREAD

**Issue by jhabdas** [aFarkas/html5shiv#210]
It's time to put this baby to bed. Please help the Web move forward by Deprecating this library. I just saw this in the WP 2017 theme and was less than impressed they're still trying to support a browser Microsoft themselves gave up on some time ago. You did great work here, @aFarkas. Let's help end the confusion by letting this library RIP. Cheers.

**Comment by jonathantneal** [comment]
It’s time to files issues with facts and evidence rather than vague personal opinions.

**Comment by jhabdas** [comment]
You seem like a delightful person, @jonathantneal. I hope we never meet.
